<a href="https://colab.research.google.com/github/Ju-06/2026-BDA/blob/main/03w_numpy_handle.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 다차원 배열 ndarray

In [22]:
import numpy as np

a= np.ndarray((2,3))
a

array([[3.25371450e-315, 0.00000000e+000, 1.33856822e-152],
       [1.63041663e-322, 3.25249059e-315, 6.76109986e-310]])

In [23]:
a= np.ndarray((2,3), dtype= int)
a

array([[          658559146,                   0, 2334675640070860897],
       [                 33,           658311424,     136846184623344]])

In [24]:
a= np.ndarray((2,3), int)
a

array([[      647889626,               0, 136845752462784],
       [136845752462848, 136845752052576, 136845752052672]])

## 내장함수 array()

In [25]:
import numpy as np

a= np.array([1,2,3], dtype=int)
a

array([1, 2, 3])

In [26]:
type(a)

numpy.ndarray

In [27]:
print(a.shape)
print(a.ndim)
print(a.dtype) # 이 친구는 왜 64로 나오는가에 대해

(3,)
1
int64


In [28]:
print(a.size)
print(a.itemsize)
print(a.nbytes)

3
8
24


## 문자열 자료형

In [32]:
np.array([1,'py', 3.14])

array(['1', 'py', '3.14'], dtype='<U32')

In [31]:
unicode_array= np.array(['가나다','라마바','사아자'], dtype='<U32')
unicode_array

array(['가나다', '라마바', '사아자'], dtype='<U32')

In [30]:
unicode_array= np.array(['가나다라마'*7,'라마바','사아자'], dtype='<U32')
unicode_array

array(['가나다라마가나다라마가나다라마가나다라마가나다라마가나다라마가나', '라마바', '사아자'], dtype='<U32')

## numpy.arange()

In [64]:
print(np.arange(3))
print(np.arange(3,7))
print(np.arange(3, 7, 2))

[0 1 2]
[3 4 5 6]
[3 5]


In [65]:
print(np.arange(2.0))
print(np.arange(2.0 , 6.5))
print(np.arange(2.0, 6.5, 0.8))

[0. 1.]
[2. 3. 4. 5. 6.]
[2.  2.8 3.6 4.4 5.2 6. ]


## 배열의 모양을 바꾸는 reshape()

In [68]:
a =np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
np.reshape(a,(2,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [71]:
np.reshape(a,(2,5))
# arange(12)랑 reshape(2,5)랑 인자? 갯수가 안맞아서 오류가 남

ValueError: cannot reshape array of size 12 into shape (2,5)

## 함수 linspace
- 그냥 만들면 기본 50개

In [33]:
np.linspace(2.0, 3.0)

array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
       2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
       2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
       2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
       2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
       2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
       2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
       2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
       2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
       2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ])

In [35]:
print((3-2)/(50-1))

0.02040816326530612


In [36]:
np.linspace(2,3,2)

array([2., 3.])

In [37]:
np.linspace(2,3,3)

array([2. , 2.5, 3. ])

In [41]:
np.linspace(2,3,3, retstep=True)
# retstep 리턴 스탭: 간격을 반환

(array([2. , 2.5, 3. ]), np.float64(0.5))

In [45]:
a = np.linspace(2,3,3, retstep=True)
a[1]
# float(a[1]) 결과값이 그냥 숫자로 나옴

0.5

In [48]:
np.linspace(2,3,3, retstep=True, endpoint=False)

(array([2.        , 2.33333333, 2.66666667]), np.float64(0.3333333333333333))

In [52]:
(3-2)/3

0.3333333333333333

In [39]:
np.linspace(2.3, 3.0, retstep=True)

(array([2.3       , 2.31428571, 2.32857143, 2.34285714, 2.35714286,
        2.37142857, 2.38571429, 2.4       , 2.41428571, 2.42857143,
        2.44285714, 2.45714286, 2.47142857, 2.48571429, 2.5       ,
        2.51428571, 2.52857143, 2.54285714, 2.55714286, 2.57142857,
        2.58571429, 2.6       , 2.61428571, 2.62857143, 2.64285714,
        2.65714286, 2.67142857, 2.68571429, 2.7       , 2.71428571,
        2.72857143, 2.74285714, 2.75714286, 2.77142857, 2.78571429,
        2.8       , 2.81428571, 2.82857143, 2.84285714, 2.85714286,
        2.87142857, 2.88571429, 2.9       , 2.91428571, 2.92857143,
        2.94285714, 2.95714286, 2.97142857, 2.98571429, 3.        ]),
 np.float64(0.014285714285714289))

## 내장함수 np.zeros()

In [53]:
np.zeros((5,), dtype=int)

array([0, 0, 0, 0, 0])

In [54]:
b = np.zeros((2,1)) # 배열
b

array([[0.],
       [0.]])

## ones()

In [56]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [57]:
np.ones((2,4), dtype=int) #dtype 지정 안하면 실수로 나옴

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

## numpy.full
- 지정한 값이 들어감

In [59]:
np.full([2,3], 10)
# 대괄호나 소괄호나 똑같음

array([[10, 10, 10],
       [10, 10, 10]])

In [62]:
np.full([4,3], fill_value = np.arange(4). reshape(4,1))

# array4 하면 1차원되는데 reshape로 이차원 배열로 만들었음 뭐?
# 그니까 행 0123을 복사해서 3열로 만들었다 이거잖어

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [63]:
np.arange(4). reshape(4,1)

array([[0],
       [1],
       [2],
       [3]])

## 배열과 스칼라와의 연산

In [73]:
# 모든 원소에 연산을 수행한 같은 모양의 배열을 반환
a = np.arange(3)
a

array([0, 1, 2])

In [74]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)

[2 3 4]
[-2 -1  0]
[0 2 4]
[0.  0.5 1. ]


## 2차원 배열의 첨자와 슬라이싱


In [75]:
a = np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [76]:
a[3]

array([18, 19, 20, 21, 22, 23])

In [77]:
a[-1]

array([24, 25, 26, 27, 28, 29])

In [78]:
a[-2,:]

array([18, 19, 20, 21, 22, 23])

In [79]:
a[-2,]

array([18, 19, 20, 21, 22, 23])

In [82]:
a[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [91]:
a[1:5:2]

array([[ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

In [92]:
# a[,1] 오류
a[:,1]

array([ 1,  7, 13, 19, 25])

In [93]:
a[:,1:6]

array([[ 1,  2,  3,  4,  5],
       [ 7,  8,  9, 10, 11],
       [13, 14, 15, 16, 17],
       [19, 20, 21, 22, 23],
       [25, 26, 27, 28, 29]])

In [95]:
a=np.arange(30).reshape(5,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [96]:
a[:,::2]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [97]:
a[2,4]

np.int64(16)

In [98]:
a[2][4]

np.int64(16)

In [99]:
a[1:3, -2:5]

array([[10],
       [16]])

In [100]:
a[:,:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [101]:
a[:,]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [102]:
a[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [103]:
a[::-1, ::-1]

array([[29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [104]:
a[:-1,:-1]
# 마지막 행과 열을 제외한 배열 반환

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

## 3차원배열

In [107]:
a = np.arange(24).reshape(2,3,4)

In [108]:

a[1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [109]:
a[:,1]

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [110]:
a[:,1,1]

array([ 5, 17])

In [111]:
a[:,:,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [112]:
a[...,1]

array([[ 1,  5,  9],
       [13, 17, 21]])

In [113]:
a[1,...,1]

array([13, 17, 21])

In [114]:
a[0,...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
a[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 브로드 캐스팅

In [116]:
a = np.array([3, 4, 5])
b = np.array([8, 7, 6])
a + b

array([11, 11, 11])

In [117]:
a = np.array([3, 4, 5, 7])
b = np.array([8, 7, 6])
a * b
# 원소 3개를 4개와 맞출 수 없어 브로드 캐스팅이 수행x

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [118]:
from numpy import arange

x = arange(1, 10).reshape(3, 3)
x



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [119]:
y = arange(-1, 2)
y

array([-1,  0,  1])

In [120]:
x * y

array([[-1,  0,  3],
       [-4,  0,  6],
       [-7,  0,  9]])

In [121]:
x + y

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [122]:
from numpy import arange
import numpy as np

x = arange(1, 10).reshape(3, 3)

In [123]:
y = arange(3, 10, 3).reshape(3, 1)

In [124]:
# 소수점 이하 자리수를 2자리로 설정
np.set_printoptions(precision=2)


In [125]:
x / y

array([[0.33, 0.67, 1.  ],
       [0.67, 0.83, 1.  ],
       [0.78, 0.89, 1.  ]])

In [126]:
x - y

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [127]:
x=arange(1,4)
x

array([1, 2, 3])

In [129]:
y = arange(1,4).reshape(3,1)
y

array([[1],
       [2],
       [3]])

In [130]:
x*y

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [131]:
x/y

array([[1.  , 2.  , 3.  ],
       [0.5 , 1.  , 1.5 ],
       [0.33, 0.67, 1.  ]])

In [132]:
x=arange(0,10,3).reshape(4,1)
x

array([[0],
       [3],
       [6],
       [9]])

In [133]:
y=arange(1,3)
y

array([1, 2])

In [134]:
x*y

array([[ 0,  0],
       [ 3,  6],
       [ 6, 12],
       [ 9, 18]])

In [135]:
x+y

array([[ 1,  2],
       [ 4,  5],
       [ 7,  8],
       [10, 11]])

In [137]:
import numpy as np
from numpy import array

x=array([0,10,20,30])
x

array([ 0, 10, 20, 30])

In [138]:
np.newaxis is None

True

In [139]:
# 차수 증감
a = x[None,:]
a

array([[ 0, 10, 20, 30]])

In [141]:
a = x[np.newaxis, :]
a

array([[ 0, 10, 20, 30]])

In [142]:
a = x[:, np.newaxis]
a

array([[ 0],
       [10],
       [20],
       [30]])

array([[ 0],
       [10],
       [20],
       [30]])

## 고급 색인

In [147]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [146]:
print(x[1])
print(x[:5])

1
[0 1 2 3 4]


In [151]:
x[2]

np.int64(2)

In [152]:
x[  [2]  ] # 인덱스로 2를 갖는 배열

array([2])

In [150]:
print(x[[2]])
print(x[[2,3]]) # 인덱스로 2, 3을 갖는 배열

[2]
[2 3]


In [156]:
x[ [2,3,5,8] ]

array([2, 3, 5, 8])

In [155]:
x[np.array([5,3,-4,8])]

array([5, 3, 6, 8])

In [158]:
x = np.arange(56).reshape(7,8)
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [159]:
x[0] # 0번째 행 전부

array([0, 1, 2, 3, 4, 5, 6, 7])

In [161]:
x[0,1] # 0행 1열 원소

int(x[0,1]) # 이건 숫자로 나옴

1

In [163]:
x[:, 2:8] # : 대신 ... 도 가능

array([[ 2,  3,  4,  5,  6,  7],
       [10, 11, 12, 13, 14, 15],
       [18, 19, 20, 21, 22, 23],
       [26, 27, 28, 29, 30, 31],
       [34, 35, 36, 37, 38, 39],
       [42, 43, 44, 45, 46, 47],
       [50, 51, 52, 53, 54, 55]])

In [165]:
x[[0], [1]]
# 0과 1을 갖는 배열
# x[0,1] 이거랑 다름
# x[ [0,1] ] 이것도 다름

array([1])

In [168]:
x

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [166]:
x[ [0,1] ]
# 0번 1번 행만 출력

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [170]:
x[ [1,3,5] ]
# 1번 3번 5번 행만 출력

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [171]:
x[ [1,3,5], : ]

array([[ 8,  9, 10, 11, 12, 13, 14, 15],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [40, 41, 42, 43, 44, 45, 46, 47]])

In [172]:
x[ [1,3], [2,2] ]
# 1행 2열, 3행 2열 인자 출력

array([10, 26])

In [174]:
x[ [1,3], [2] ]
# 1행 3행에 2열 원소만

array([10, 26])

In [175]:
x[ [1,3], [2,3] ]

array([10, 27])

In [177]:
a = arange(40).reshape(5,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [178]:
a[2:4, 3:7]

array([[19, 20, 21, 22],
       [27, 28, 29, 30]])

In [179]:
a[arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [180]:
a[arange(2,4)][:, [1,0]]

array([[17, 16],
       [25, 24]])

In [183]:
a[arange(2,5)][:, [1,0,3,5]]

array([[17, 16, 19, 21],
       [25, 24, 27, 29],
       [33, 32, 35, 37]])

In [184]:
a[arange(2,5)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [185]:
a[arange(2,5)][:, arange(-1, -8, -1)]

array([[23, 22, 21, 20, 19, 18, 17],
       [31, 30, 29, 28, 27, 26, 25],
       [39, 38, 37, 36, 35, 34, 33]])

In [182]:
a[np.arange(2,4)]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [186]:
a[np.arange(2,4)][:, [1,1,1]]

array([[17, 17, 17],
       [25, 25, 25]])

In [187]:
a[[2,3,4]]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])

In [189]:
a[[2,3,4]][:, ::-1]

SyntaxError: invalid syntax (1239665794.py, line 1)